version: "3.8"

services:
  mongodb:
    image: mongo:5.0
    container_name: mongodb-forum
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: forum-db
    volumes:
      - mongo_data:/data/db
volumes:
  mongo_data:
    driver: local